In [2]:
import numpy as np
from scipy.optimize import minimize


In [3]:
#Task 1: Create a zero matrix
zero_matrix = np.zeros((3, 3))
print("Zero Matrix:\n", zero_matrix)

Zero Matrix:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
# Task 2: Create an identity matrix
identity_matrix = np.eye(3)
print("Identity Matrix:\n", identity_matrix)

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
# Task 3: Create a random matrix
random_matrix = np.random.rand(3, 3)
print("Random Matrix:\n", random_matrix)

Random Matrix:
 [[0.61462445 0.05770168 0.59173269]
 [0.66370649 0.72365979 0.005419  ]
 [0.91679549 0.72301184 0.81393541]]


In [7]:
# Task 4: Basic matrix operations
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = A + B
print("Matrix Addition:\n", C)
D = A - B
print("Matrix Subtraction:\n", D)
E = np.dot(A, B)
print("Matrix Multiplication:\n", E)

Matrix Addition:
 [[ 6  8]
 [10 12]]
Matrix Subtraction:
 [[-4 -4]
 [-4 -4]]
Matrix Multiplication:
 [[19 22]
 [43 50]]


In [8]:
# Task 5: Transpose a matrix
transpose_A = A.T
print("Transpose of Matrix A:\n", transpose_A)

Transpose of Matrix A:
 [[1 3]
 [2 4]]


In [9]:
# Task 6: Find the determinant and inverse of a matrix
det_A = np.linalg.det(A)
inv_A = np.linalg.inv(A)
print("Determinant of A:", det_A)
print("Inverse of A:\n", inv_A)

Determinant of A: -2.0000000000000004
Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [10]:
# Task 7: Solve a system of linear equations
b = np.array([5, 6])
x = np.linalg.solve(A, b)
print("Solution to the system of equations:", x)

Solution to the system of equations: [-4.   4.5]


In [11]:
# Task 11: Basic vector operations (addition, dot product, cross product)
v1 = np.array([1, 2])
v2 = np.array([3, 4])
v_sum = v1 + v2
v_dot_product = np.dot(v1, v2)
v_cross_product = np.cross(v1, v2)
print("Vector Sum:", v_sum)
print("Dot Product:", v_dot_product)
print("Cross Product:", v_cross_product)

Vector Sum: [4 6]
Dot Product: 11
Cross Product: -2


In [12]:
# Task: Normalize a vector and compute vector norms
norm_v1 = np.linalg.norm(v1)
normalized_v1 = v1 / norm_v1
print("Norm of v1:", norm_v1)
print("Normalized v1:", normalized_v1)

Norm of v1: 2.23606797749979
Normalized v1: [0.4472136  0.89442719]


In [13]:
# Compute the numerical derivative of a given function
def f(x):
    return x**2 + np.sin(x)

def numerical_derivative(func, x, h=1e-6):
    return (func(x + h) - func(x)) / h

x = 1.0
derivative = numerical_derivative(f, x)
print(f'Numerical derivative at x={x}: {derivative}')

Numerical derivative at x=1.0: 2.54030288515672


In [14]:
# Compute the numerical integral of a given function
def f(x):
    return np.sin(x)

def numerical_integral(func, a, b, method='trapezoidal', N=1000):
    x = np.linspace(a, b, N)
    dx = (b - a) / N
    
    if method == 'trapezoidal':
        integral = np.trapz(func(x), x)
    elif method == 'simpson':
        integral = np.sum(dx / 3 * (func(x[0]) + 4*func(x[1:-1:2]).sum() + 2*func(x[2:-2:2]).sum() + func(x[-1])))
    else:
        raise ValueError(f'Method {method} is not supported.')

    return integral

a, b = 0, np.pi
integral_trapezoidal = numerical_integral(f, a, b, method='trapezoidal')
integral_simpson = numerical_integral(f, a, b, method='simpson')
print(f'Numerical integral using Trapezoidal rule: {integral_trapezoidal}')
print(f'Numerical integral using Simpson\'s rule: {integral_simpson}')


Numerical integral using Trapezoidal rule: 1.999998351770852
Numerical integral using Simpson's rule: 1.9979917671073473


In [15]:
# Calculate partial derivatives of multivariable functions
def f(x, y):
    return x**2 + y**3

def partial_derivative(func, var='x', point=(1, 2), h=1e-6):
    if var == 'x':
        return (func(point[0] + h, point[1]) - func(point[0], point[1])) / h
    elif var == 'y':
        return (func(point[0], point[1] + h) - func(point[0], point[1])) / h
    else:
        raise ValueError(f'Variable {var} is not supported.')

In [16]:
# Example usage
partial_x = partial_derivative(f, var='x', point=(1, 2))
partial_y = partial_derivative(f, var='y', point=(1, 2))
print(f'Partial derivative with respect to x: {partial_x}')
print(f'Partial derivative with respect to y: {partial_y}')

Partial derivative with respect to x: 2.0000010003684565
Partial derivative with respect to y: 12.000006002210739


In [17]:
# Solve optimization problems with constraints
def objective(x):
    return x[0]**2 + x[1]**2

def constraint(x):
    return x[0] + x[1] - 1

initial_guess = [0.5, 0.5]
bounds = [(-1, 1), (-1, 1)]
constraint_obj = {'type': 'eq', 'fun': constraint}

result = minimize(objective, initial_guess, bounds=bounds, constraints=constraint_obj)
print(f'Optimal solution: {result.x}')

Optimal solution: [0.5 0.5]
